## Data Pre-processing

#### Required Modules

In [2]:
import os
import pandas as pd
import numpy as np

#### Constants

In [3]:
DATA = os.path.join('..', 'data')

#### Helper Functions

Method to load data from the `data/raw/` directory.

In [4]:
def load_dataset(filename: str) -> pd.DataFrame:
    """Returns raw dataset."""
    return pd.read_csv(os.path.join(DATA, 'raw', filename))

### **1.** Insurance Dataset

In [5]:
INSURANCE = 'insurance.csv'


insurance = load_dataset(INSURANCE)
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

Transform float `bmi` column into a categorical feature.

In [6]:
if "bmi" in insurance.columns:
    
    bins = [-np.inf, 18.5, 24.9, 29.9, np.inf]
    labels = [
        "0_UNDERWEIGHT", "1_HEALTHY",
        "2_OVERWEIGHT", "3_OBESITY"]

    insurance["BMI_CATEGORY"] = pd.cut(
        insurance["bmi"],
        bins=bins,
        labels=labels)

    insurance = insurance.drop("bmi", axis=1)

insurance.head()

   age     sex  children smoker     region      charges  BMI_CATEGORY
0   19  female         0    yes  southwest  16884.92400  2_OVERWEIGHT
1   18    male         1     no  southeast   1725.55230     3_OBESITY
2   28    male         3     no  southeast   4449.46200     3_OBESITY
3   33    male         0     no  northwest  21984.47061     1_HEALTHY
4   32    male         0     no  northwest   3866.85520  2_OVERWEIGHT

Simplify integer `children` column into boolean flag.

In [7]:
if "children" in insurance.columns:
    
    has_children = insurance["children"] >= 1
    insurance["HAS_CHILDREN"] = has_children
    
    insurance = insurance.drop("children", axis=1)

insurance.head()

   age     sex smoker     region      charges  BMI_CATEGORY  HAS_CHILDREN
0   19  female    yes  southwest  16884.92400  2_OVERWEIGHT         False
1   18    male     no  southeast   1725.55230     3_OBESITY          True
2   28    male     no  southeast   4449.46200     3_OBESITY          True
3   33    male     no  northwest  21984.47061     1_HEALTHY         False
4   32    male     no  northwest   3866.85520  2_OVERWEIGHT         False

Convert float `charges` column to categorical values (quartiles).

In [8]:
if "charges" in insurance.columns:

    insurance['LABEL'] = pd.qcut(
        insurance['charges'],
        q=5,
        labels=[
            'Q1', 'Q2', 'Q3', 'Q4', 'Q5'])

    insurance = insurance.drop("charges", axis=1)

insurance.head()

   age     sex smoker     region  BMI_CATEGORY  HAS_CHILDREN LABEL
0   19  female    yes  southwest  2_OVERWEIGHT         False    Q4
1   18    male     no  southeast     3_OBESITY          True    Q1
2   28    male     no  southeast     3_OBESITY          True    Q2
3   33    male     no  northwest     1_HEALTHY         False    Q5
4   32    male     no  northwest  2_OVERWEIGHT         False    Q1

Standardize column names.

In [9]:
rename_map = {
    "age": "AGE", "sex": "SEX",
    "smoker": "SMOKER", "region": "REGION"}
insurance = insurance.rename(columns=rename_map)

insurance.head()

   AGE     SEX SMOKER     REGION  BMI_CATEGORY  HAS_CHILDREN LABEL
0   19  female    yes  southwest  2_OVERWEIGHT         False    Q4
1   18    male     no  southeast     3_OBESITY          True    Q1
2   28    male     no  southeast     3_OBESITY          True    Q2
3   33    male     no  northwest     1_HEALTHY         False    Q5
4   32    male     no  northwest  2_OVERWEIGHT         False    Q1

Save data.

In [10]:
filepath = os.path.join(DATA, INSURANCE)
insurance.to_csv(filepath, index=False)

### **2.** Personality Dataset

In [11]:
PERSONALITY = 'personality.csv'


personality = load_dataset(PERSONALITY)
personality.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,3,Yes,6,7,No,14,5,Extrovert
1,2,No,8,6,No,7,8,Extrovert
2,1,No,9,4,No,9,3,Extrovert
3,8,No,0,0,Yes,9,3,Introvert
4,5,Yes,3,0,No,2,6,Introvert

Transform integer `Time_spent_Alone` column into categorical values.

In [12]:
if "Time_spent_Alone" in personality.columns:
    
    bins = [-np.inf, 3.5, 7.5, np.inf]
    labels = [
        "0_LOW", "1_MEDIUM",
        "2_HIGH"]

    personality["TIME_ALONE"] = pd.cut(
        personality["Time_spent_Alone"],
        bins=bins,
        labels=labels)

    personality = personality.drop("Time_spent_Alone", axis=1)

personality.head()

,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality,TIME_ALONE
0,Yes,6,7,No,14,5,Extrovert,0_LOW
1,No,8,6,No,7,8,Extrovert,0_LOW
2,No,9,4,No,9,3,Extrovert,0_LOW
3,No,0,0,Yes,9,3,Introvert,2_HIGH
4,Yes,3,0,No,2,6,Introvert,1_MEDIUM

Transform integer `Social_event_attendance` column into categorical values.

In [13]:
if "Social_event_attendance" in personality.columns:
    
    bins = [-np.inf, 3.5, 7.5, np.inf]
    labels = [
        "0_RARE", "1_MODERATE",
        "2_FREQUENT"]

    personality["EVENT_ATTENDANCE"] = pd.cut(
        personality["Social_event_attendance"],
        bins=bins,
        labels=labels)

    personality = personality.drop("Social_event_attendance", axis=1)

personality.head()

,Stage_fear,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality,TIME_ALONE,EVENT_ATTENDANCE
0,Yes,7,No,14,5,Extrovert,0_LOW,1_MODERATE
1,No,6,No,7,8,Extrovert,0_LOW,2_FREQUENT
2,No,4,No,9,3,Extrovert,0_LOW,2_FREQUENT
3,No,0,Yes,9,3,Introvert,2_HIGH,0_RARE
4,Yes,0,No,2,6,Introvert,1_MEDIUM,0_RARE

Standardize column names.

In [14]:
rename_map = {
    "Stage_fear": "STAGE_FEAR",
    "Drained_after_socializing": "SOCIAL_DRAIN",
    "Going_outside": "GOING_OUTSIDE",
    "Friends_circle_size": "FRIEND_CIRCLE",
    "Post_frequency": "POST_FREQUENCY",
    "Personality": "PERSONALITY"}
personality = personality.rename(columns=rename_map)

personality.head()

,STAGE_FEAR,GOING_OUTSIDE,SOCIAL_DRAIN,FRIEND_CIRCLE,POST_FREQUENCY,PERSONALITY,TIME_ALONE,EVENT_ATTENDANCE
0,Yes,7,No,14,5,Extrovert,0_LOW,1_MODERATE
1,No,6,No,7,8,Extrovert,0_LOW,2_FREQUENT
2,No,4,No,9,3,Extrovert,0_LOW,2_FREQUENT
3,No,0,Yes,9,3,Introvert,2_HIGH,0_RARE
4,Yes,0,No,2,6,Introvert,1_MEDIUM,0_RARE

Save data.

In [15]:
filepath = os.path.join(DATA, PERSONALITY)
personality.to_csv(filepath, index=False)

¯\\\_(ツ)\_/¯